### ISSUE TITLE
Testrules location

### ISSUE THREAD

**Issue by ylavoie** [pjlsergeant/test-bdd-cucumber-perl#111]
Prove should also look into directories specified on the command line for testrules.yml
Currently, only t/ is searched, along with what is specified by HARNESS_RULESFILE environment variable.

**Comment by pjlsergeant** [comment]
Again, this sounds like an issue with `prove`. @ehuelsmann what do you think?

**Comment by ylavoie** [comment]
Yes, both are. My bad.

**Comment by pjlsergeant** [comment]
No problem, thanks for continuing to support the project

**Comment by ehuelsmann** [comment]
Closing, as @ylavoie agrees it's not a problem for TBC.
