### ISSUE TITLE
Validating HTML/XML

### ISSUE THREAD

**Issue by yokall** [pjlsergeant/test-bdd-cucumber-perl#112]
In some of our steps we check HTML and pass in the HTML in the data table.

| html              |
| <p>Text</p> |

After upgrading to version 0.50 these steps throw an error because it treats the <> brackets as placeholders.  I've tried escaping them with backslashes, wrapping the whole string in single and double quotes but it keeps throwing the same error.  Is there a way to get around this?  I could encode the HTML and update the step to handle this but if there is a way for me not to have to update step code and definitions that would be preferable.

**Comment by pjlsergeant** [comment]
I'm afraid I can't think of anything useful here. Simplest solution is probably to use a Step transform to decode them?

https://github.com/cucumber/cucumber/wiki/Step-Argument-Transforms

**Comment by yokall** [comment]
Thank you for your reply, I will look into Step Transforms
