### ISSUE TITLE
ParserOld.pm shipped in the 0.52 dist: by mistake?

### ISSUE THREAD

**Issue by intrigeri** [pjlsergeant/test-bdd-cucumber-perl#122]
Hi Peter,

while packaging 0.52 for Debian I saw autopkgtest failures due to ParserOld.pm: it's shipped in the tarball, and depends on File::Slurp while this dependency was removed elsewhere. I don't see this file in Git.

Is this file included on purpose? Should we distribute it in Debian?

**Comment by pjlsergeant** [comment]
0.53, just uploaded to CPAN, removes this file

-P

**Comment by pjlsergeant** [comment]
Fixed in 0.53, thanks
