### ISSUE TITLE
What do you mean by "quoting in tables is broken"?

### ISSUE THREAD

**Issue by JJ** [pjlsergeant/test-bdd-cucumber-perl#50]
Some specific test you are referring to or piece of code? I might be able to help.

**Comment by ehuelsmann** [comment]
Well, reading the code in Test::BDD::Cucumber::Parser(pipe_array), I'm expecting it to mean that it's impossible to hold data in a table which contains a "pipe" (|) character. There's no detection of "escaped" pipes and there's no unescaping of data going on.
