### ISSUE TITLE
Configuration and extensions such as with Behat?

### ISSUE THREAD

**Issue by ehuelsmann** [pjlsergeant/test-bdd-cucumber-perl#65]
Hi,

Over at the LedgerSMB project, we've started using pherkin to write BDD tests. While we can run our tests as part of 'make test' using your example t/900-* script, I'm using the pherkin binary all the time to run *just* the BDD tests, or even part thereof.
In our own t/900-* runner script, I can stop at every feature and run pre- and post-processing hooks. However, when I'm using the pherkin script binary, that's not supported out of the box. In Behat (PHP's Cucumber), Behat reads a configuration file and uses that to trigger/initialize extensions.

Is there an option to do the same here, so I:

a. don't need to write that code into my t/* scripts; and
b. this will be supported by any testing method -- regardless of the method of execution being pherkin or t/*

Thanks for your consideration!

Erik.
PS: If you think this could be a good idea and you have some ideas how to arrange for it, I might be able to send you a PR. I'll gladly discuss further here or over e-mail (or in another discussion forum, mailing list?)

**Comment by pjlsergeant** [comment]
Please could you give me an example of something you're explicitly loading in your t/ script? For example, a shortened version of your test-runner?

**Comment by ehuelsmann** [comment]
I actually haven't implemented this yet (I've been studying the Test::BDD::Cucumber code and found that I can't due to the fact that the feature stash isn't stored in the feature), but what I'd *want* to implement is something along these lines:

````perl
    my $config = new YAML( $ENV{BDD_CONFIG} );
    my @extensions = $_->new( config => $config ) for @{$config->{extensions}};
    my ( $executor, @features ) =
        Test::BDD::Cucumber::Loader->load('t/66-cucumber/' . $directory);
    die "No features found" unless @features;

    foreach my $feature (@features) {
        $_->pre_feature( $feature ) for @extensions;
        $executor->execute( $feature, $harness );
        $_->post_feature( $feature ) for @extensions;
    }
````

in one of the ````pre_feature```` extension methods (actually *the* extension I'm now looking to create), I'll want to do this:

````perl
sub pre_feature {
   my ($self, $feature) = @_;
   $feature->{stash}->{driver} =
      Selenium::Remote::Driver->new( port => 4422 );
   $feature->{stash}->{dbh} = DBI->connect();
   # do database setup
}
````

````perl
sub post_feature {
   my ($self, $feature) = @_;
   if (! $feature->failed) {
      # on failure, leave the database for developer inspection
      $feature->{stash}->{dbh}->destroy_database;
   }
}
````

In addition to the above, the next step I'd be looking at is to trap success/ failure of steps, scenarios and features.

If you would like me to, I could submit the beginnings of a proposal using a PR?
