### ISSUE TITLE
Amend authors section

### ISSUE THREAD

**Issue by pjlsergeant** [pjlsergeant/test-bdd-cucumber-perl#83]
Should probably mention @ehuelsmann

**Comment by ehuelsmann** [comment]
@pjlsergeant there are (at least) two author sections; the one in README.pod (= lib/Test/BDD/Cucumber.pm) already lists me. The other one (used in pod2usage) is in bin/pherkin. This one lists *only* you (not Ben). As such, I think this issue is addressed and can be closed.
