### ISSUE TITLE
Wide character in print at /usr/lib/perl5/site_perl/5.14/Test/Builder.pm line 1826.

### ISSUE THREAD

**Issue by dokechin** [pjlsergeant/test-bdd-cucumber-perl#91]
I wrote a feature file in Japanese (Muiti byte string).
And then pherkin command issued then print out ”Wide character in print”.
I have tryed change code TestBuiler.pm to use Test::More::UTF8 instead of
Test::More, but became not to pass test.

**Comment by pjlsergeant** [comment]
Please could you send me as much of the code as you're willing to share to
look at?

**Comment by dokechin** [comment]
Uploaded source to 
https://github.com/dokechin/test-bdd-cucumber-perl/tree/multibyte

I am using Test::BDD::Cucumber module example below.(Japanese feature file exists)
https://github.com/dokechin/cucumber_example

**Comment by pjlsergeant** [comment]
I think the issue here is with `Test::Selenium::Remote::Driver`. I suspect you're best off explicitly encoding your regex before testing:

From:
```perl
  my $mj = sprintf("%sMJ" , C->matches->[0]);
  S->{'sel'}->body_text_like(qr/$mj/);
```

To something like:

```perl
  my $mj = sprintf("%sMJ" , C->matches->[0]);
  utf8::encode( $mj );
  S->{'sel'}->body_text_like(qr/$mj/);
```

You could save yourself typing that each time by defining:
```perl
sub encoded_body_text_like {
  my ( $class, $regex ) = @_;
  utf8::encode( $regex );
  S->{'sel'}->body_text_like( qw/$regex/ );
}
```

**Comment by dokechin** [comment]
Thank you very much.
I tryed again its code. but still output.
I think the place where "wide character in print" output is step name outputting phase.

**Comment by pjlsergeant** [comment]
OK, I'll take another look
